"use client";

import { ArrowRight, Check, GitCompareArrows } from "lucide-react";
import type { CreditCard, ScoredCard } from "@/src/lib/types";
import { formatFee } from "@/src/lib/format";
import { Button } from "@/src/components/ui/Button";
import { GlassCard } from "@/src/components/ui/GlassCard";
import { ScrollReveal } from "@/src/components/ui/ScrollReveal";

export type TopPicksProps = { cards: CreditCard[]; selected: ScoredCard[]; onToggle: (card: CreditCard) => void };

export function TopPicks({ cards, selected, onToggle }: TopPicksProps) {
  return <div className="grid gap-5 lg:grid-cols-3">{cards.map((card, index) => { const checked = selected.some((item) => item.card.id === card.id); return <ScrollReveal key={card.id} delay={index * .08}><GlassCard className="group relative overflow-hidden p-5 transition duration-500 hover:-translate-y-2 hover:border-teal-400/50 hover:bg-surface-2"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-teal-400 to-amber-300" />{index === 0 && <span className="absolute right-5 top-5 rounded-full bg-amber-300 px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-slate-950">Editor&apos;s pick</span>}<div className={`relative flex min-h-52 flex-col justify-between overflow-hidden rounded-2xl border border-white/15 bg-gradient-to-br ${card.gradient} p-5`}><div className="flex justify-between"><span className="text-[10px] font-bold tracking-[.2em] text-white/60">{card.issuer.toUpperCase()}</span><span className="font-black text-amber-200">JC</span></div><div><div className="h-9 w-12 rounded-md border border-amber-100/50 bg-gradient-to-br from-amber-100 to-amber-500" /><p className="mt-4 text-xs tracking-[.2em] text-white/60">•••• 4821</p></div></div><div className="mt-5"><h3 className="text-xl font-bold text-ink">{card.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-muted">{card.tagline}</p></div><div className="mt-5 flex items-center justify-between border-y border-border py-4 text-sm"><span className="text-muted">Annual fee</span><strong className="text-ink">{formatFee(card.annualFee)}</strong></div><ul className="mt-4 space-y-2">{card.highlights.slice(0, 2).map((highlight) => <li key={highlight} className="flex gap-2 text-sm text-muted"><Check aria-hidden="true" className="mt-1 h-4 w-4 shrink-0 text-teal-400" />{highlight}</li>)}</ul><div className="mt-5 flex gap-2"><Button href="#card-match" className="flex-1">Apply now<ArrowRight aria-hidden="true" className="h-4 w-4" /></Button><button type="button" aria-pressed={checked} aria-label={`${checked ? "Remove" : "Add"} ${card.name} from comparison`} onClick={() => onToggle(card)} className={`focus-ring inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border transition ${checked ? "border-teal-400 bg-teal-400/15 text-teal-400" : "border-border text-muted hover:border-teal-400/50 hover:text-teal-400"}`}><GitCompareArrows aria-hidden="true" className="h-5 w-5" /></button></div></GlassCard></ScrollReveal>; })}</div>;
}
